### ISSUE TITLE
Not an issue but trying to reach you !

### ISSUE THREAD

**Issue by ShalomJunior** [LiquidFun/FSR-Coding-Cup-2023#1]
Hello. I hope you are doing well. My name is Junior.
I have found your contest interesting. I would like to use it as a contest between friends and some people that are beginner at CP.
Can you please grant me access to it on codeforces so that i  can clone the problems ? 
Looking forward to reading you soon. We plan to do the contest tomorrow. My codeforces handle is __fn__

**Comment by LiquidFun** [comment]
Hey, sure! I don't see a user with the name `fn` though? Can you send me a link to your profile, like this? https://codeforces.com/profile/fn

**Comment by LiquidFun** [comment]
Ah your name is `__fn__`, I guess bad luck with formatting. Here is an invite link: https://codeforces.com/contestInvitation/06bc595f03f784ae7b8e711fd772dae6014ab45d. Let me know if that works and you can clone it
